# Generated by Django 4.0.1 on 2022-01-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_snippet_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ['updated']},
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='upddated',
            new_name='updated',
        ),
    ]
